# Generated by GitHub Copilot
"""
Test script for HuggingFace API Embeddings

This script verifies that:
1. HuggingFace API token is configured correctly
2. Embeddings can be generated via the API
3. The MicrolearningGenerator works with HuggingFace API
"""

import os
import sys
from pathlib import Path
import requests
from dotenv import load_dotenv

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent))

# Load environment variables
env_path = Path(__file__).parent / ".env"
load_dotenv(env_path)

print("="*80)
print("🧪 TESTING HUGGINGFACE API INTEGRATION")
print("="*80)

# Test 1: Environment Variables
print("\n📋 Test 1: Checking Environment Variables")
print("-"*80)

groq_api_key = os.getenv("GROQ_API_KEY")
hf_token = os.getenv("HUGGINGFACE_API_TOKEN")

if not groq_api_key:
    print("❌ GROQ_API_KEY not found in .env")
    sys.exit(1)
else:
    print(f"✅ GROQ_API_KEY found: {groq_api_key[:20]}...")

if not hf_token:
    print("❌ HUGGINGFACE_API_TOKEN not found in .env")
    sys.exit(1)
else:
    print(f"✅ HUGGINGFACE_API_TOKEN found: {hf_token[:20]}...")

# Test 2: Direct HuggingFace API Call
print("\n📋 Test 2: Testing HuggingFace Inference API")
print("-"*80)

model_name = "sentence-transformers/all-MiniLM-L6-v2"
api_url = f"https://api-inference.huggingface.co/pipeline/feature-extraction/{model_name}"
headers = {"Authorization": f"Bearer {hf_token}"}

test_texts = ["Hello world", "Testing HuggingFace API"]

print(f"🌐 Calling HuggingFace API...")
print(f"   Model: {model_name}")
print(f"   Texts: {test_texts}")

try:
    response = requests.post(
        api_url,
        headers=headers,
        json={"inputs": test_texts, "options": {"wait_for_model": True}},
        timeout=30
    )
    
    print(f"   Status Code: {response.status_code}")
    
    if response.status_code == 200:
        embeddings = response.json()
        print(f"✅ API call successful!")
        print(f"   Embeddings received: {len(embeddings)} vectors")
        print(f"   Embedding dimension: {len(embeddings[0])}")
        if len(embeddings[0]) == 384:
            print(f"✅ Correct dimension for all-MiniLM-L6-v2 model (384)")
        else:
            print(f"⚠️  Unexpected dimension (expected 384, got {len(embeddings[0])})")
    else:
        print(f"❌ API call failed!")
        print(f"   Response: {response.text}")
        sys.exit(1)
        
except requests.exceptions.Timeout:
    print(f"❌ Request timed out (30 seconds)")
    print(f"   The model might be loading. Try again in a moment.")
    sys.exit(1)
except Exception as e:
    print(f"❌ Error: {e}")
    sys.exit(1)

# Test 3: HuggingFaceEmbeddings Class
print("\n📋 Test 3: Testing HuggingFaceEmbeddings Class")
print("-"*80)

try:
    from src.microlearning_generator import HuggingFaceEmbeddings
    
    print("🔄 Initializing HuggingFaceEmbeddings...")
    embedder = HuggingFaceEmbeddings(model_name, hf_token)
    print(f"✅ HuggingFaceEmbeddings initialized")
    
    print(f"\n🔄 Generating embeddings...")
    test_inputs = ["Sustainability", "Climate change"]
    embeddings = embedder.encode(test_inputs)
    
    print(f"✅ Embeddings generated successfully!")
    print(f"   Number of embeddings: {len(embeddings)}")
    print(f"   Embedding dimension: {len(embeddings[0])}")
    
    dimension = embedder.get_sentence_embedding_dimension()
    print(f"   Reported dimension: {dimension}")
    
    if dimension == 384 and len(embeddings[0]) == 384:
        print(f"✅ All dimension checks passed!")
    else:
        print(f"⚠️  Dimension mismatch")
    
except ImportError as e:
    print(f"❌ Failed to import HuggingFaceEmbeddings")
    print(f"   Error: {e}")
    sys.exit(1)
except Exception as e:
    print(f"❌ Error testing HuggingFaceEmbeddings: {e}")
    sys.exit(1)

# Test 4: MicrolearningGenerator (if vector store exists)
print("\n📋 Test 4: Testing MicrolearningGenerator")
print("-"*80)

vector_store_path = Path(__file__).parent / "vector_store"

if not vector_store_path.exists():
    print(f"⚠️  Vector store not found at: {vector_store_path}")
    print(f"   Run the data ingestion notebook first to create the vector store")
    print(f"   Skipping MicrolearningGenerator test")
else:
    try:
        from src.microlearning_generator import create_generator_from_env
        
        print(f"🔄 Initializing MicrolearningGenerator...")
        generator = create_generator_from_env()
        print(f"✅ MicrolearningGenerator initialized successfully!")
        
        # Check collection
        collection_count = generator.collection.count()
        print(f"   Vector store chunks: {collection_count:,}")
        
        if collection_count == 0:
            print(f"⚠️  Vector store is empty. Run the data ingestion notebook.")
        else:
            print(f"✅ Vector store contains data!")
            
            # Test retrieval
            print(f"\n🔄 Testing content retrieval...")
            test_category = "circular_economy_and_waste_reduction"
            chunks = generator.retrieve_category_content(test_category, top_k=5)
            
            if chunks:
                print(f"✅ Successfully retrieved {len(chunks)} chunks for '{test_category}'")
                print(f"   Sample chunk preview: {chunks[0][:100]}...")
            else:
                print(f"⚠️  No chunks found for category: {test_category}")
        
    except Exception as e:
        print(f"❌ Error testing MicrolearningGenerator: {e}")
        import traceback
        traceback.print_exc()

# Summary
print("\n" + "="*80)
print("✅ ALL TESTS PASSED!")
print("="*80)
print("\n🎯 Summary:")
print("   ✅ HuggingFace API token configured")
print("   ✅ HuggingFace Inference API working")
print("   ✅ HuggingFaceEmbeddings class functional")
if vector_store_path.exists():
    print("   ✅ MicrolearningGenerator initialized")
else:
    print("   ⚠️  Vector store not created yet (run data ingestion notebook)")

print("\n🚀 Next Steps:")
if not vector_store_path.exists():
    print("   1. Run the data ingestion notebook to create vector store")
    print("   2. Update notebooks with HuggingFace API (see HUGGINGFACE_API_UPDATE_GUIDE.md)")
    print("   3. Test the API endpoint")
else:
    print("   1. Start the API: cd src && uvicorn mcq_api_service:app --reload")
    print("   2. Test micro-learning endpoint")
    print("   3. Deploy to production!")

print("\n📚 Documentation:")
print("   - HUGGINGFACE_API_UPDATE_GUIDE.md - Detailed update instructions")
print("   - MICROLEARNING_README.md - Complete API documentation")
print("   - QUICK_START.md - Quick reference guide")
