"""
Chat History Database Module

This module handles database operations for the WWF Chatbot.
Supports both SQLite (local development) and PostgreSQL (production on Render).

Generated by GitHub Copilot
"""

import os
from sqlalchemy import create_engine, Column, String, Integer, DateTime, Text, JSON
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

# Auto-detect database URL (works for both SQLite and PostgreSQL)
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL is None:
    # Local development - use SQLite
    DATABASE_URL = "sqlite:///./chat_history.db"
    logger.info("⚠️  Using SQLite for local development")
elif DATABASE_URL.startswith("postgres://"):
    # Render uses "postgres://" but SQLAlchemy needs "postgresql://"
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
    logger.info("✅ Using PostgreSQL (Production)")
else:
    logger.info("✅ Using configured database")

# Create engine
engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True,  # Verify connections before using
    echo=False  # Set to True for SQL debugging
)

# Create session factory
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# Base class for models
Base = declarative_base()


# ==================== Database Models ====================

class User(Base):
    """User information table"""
    __tablename__ = "users"
    
    user_id = Column(String, primary_key=True)
    name = Column(String)
    education = Column(String, nullable=True)
    location = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


class ChatSession(Base):
    """Chat session tracking table"""
    __tablename__ = "chat_sessions"
    
    session_id = Column(String, primary_key=True)
    user_id = Column(String, index=True)
    started_at = Column(DateTime, default=datetime.utcnow)
    last_activity = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class ChatMessage(Base):
    """Individual chat messages table"""
    __tablename__ = "chat_messages"
    
    message_id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String, index=True)
    user_id = Column(String, index=True)
    role = Column(String)  # 'user' or 'assistant'
    content = Column(Text)
    message_metadata = Column(JSON, nullable=True)  # stores source info (rag/web), citations, agent_used, etc.
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)


# ==================== Database Functions ====================

def init_db():
    """Create all database tables"""
    try:
        Base.metadata.create_all(bind=engine)
        logger.info("✅ Database tables created successfully")
    except Exception as e:
        logger.error(f"❌ Failed to create database tables: {e}")
        raise


def get_db():
    """
    Dependency function for FastAPI to get database session.
    
    Usage in FastAPI endpoint:
        @app.post("/endpoint")
        async def endpoint(db: Session = Depends(get_db)):
            # Use db here
    """
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


# ==================== Helper Functions ====================

def get_database_info():
    """Get information about the current database connection"""
    return {
        "database_type": "PostgreSQL" if "postgresql" in DATABASE_URL else "SQLite",
        "url": DATABASE_URL.split("@")[-1] if "@" in DATABASE_URL else "sqlite://./chat_history.db"
    }
