# Generated by GitHub Copilot
"""
Pydantic models for chatbot API
"""
from pydantic import BaseModel, Field, field_validator
from typing import Optional, List, Literal
from datetime import datetime


class UserContext(BaseModel):
    """User context information"""
    user_id: str = Field(..., description="Unique user identifier")
    name: str = Field(..., description="User's name")
    education: str = Field(..., description="User's educational background")
    location: str = Field(..., description="User's location (city, state/country)")
    
    @field_validator('user_id', 'name', 'education', 'location')
    @classmethod
    def validate_not_empty(cls, v):
        if not v or not v.strip():
            raise ValueError('Field cannot be empty')
        return v.strip()


class InitSessionRequest(BaseModel):
    """Request to initialize a new chat session"""
    user_id: str
    name: str
    education: str
    location: str


class InitSessionResponse(BaseModel):
    """Response after session initialization"""
    session_id: str
    user_id: str
    message: str
    welcome_message: str


class Source(BaseModel):
    """Source citation for responses"""
    type: Literal['rag', 'web_search']
    title: str
    url: Optional[str] = None
    excerpt: str


class SendMessageRequest(BaseModel):
    """Request to send a message in chat"""
    session_id: str
    user_id: str
    message: str
    
    @field_validator('message')
    @classmethod
    def validate_message(cls, v):
        if not v or not v.strip():
            raise ValueError('Message cannot be empty')
        if len(v) > 2000:
            raise ValueError('Message too long (max 2000 characters)')
        return v.strip()


class SendMessageResponse(BaseModel):
    """Response to user message"""
    message_id: str
    response: str
    sources: List[Source] = []
    agent_used: Literal['rag', 'web_search', 'hybrid', 'pdf_export']
    timestamp: str
    pdf_url: Optional[str] = None  # Only present if PDF was generated


class ChatMessageDTO(BaseModel):
    """Chat message data transfer object"""
    role: Literal['user', 'assistant']
    content: str
    sources: Optional[List[Source]] = None
    timestamp: str


class ChatHistoryResponse(BaseModel):
    """Response containing chat history"""
    session_id: str
    messages: List[ChatMessageDTO]


class ChatSessionSummary(BaseModel):
    """Summary of a chat session"""
    session_id: str
    started_at: str
    last_activity: str
    message_count: int
    preview: Optional[str] = None


class UserSessionsResponse(BaseModel):
    """Response containing user's chat sessions"""
    user_id: str
    sessions: List[ChatSessionSummary]


class PDFExportResponse(BaseModel):
    """Response for PDF export"""
    pdf_url: str
    download_link: str
    session_id: str


class AgentState(BaseModel):
    """Internal state for LangGraph agents"""
    query: str
    user_context: UserContext
    rag_context: Optional[str] = None
    web_context: Optional[str] = None
    agent_route: Optional[Literal['rag', 'web_search', 'hybrid', 'pdf_export']] = None
    response: Optional[str] = None
    sources: List[Source] = []
    pdf_requested: bool = False
    pdf_url: Optional[str] = None
    
    class Config:
        arbitrary_types_allowed = True
