# Generated by GitHub Copilot
"""
PDF Export Generator - Creates PDF exports of chat conversations
"""
import os
import logging
from pathlib import Path
from datetime import datetime
from typing import List, Dict
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_LEFT, TA_CENTER

logger = logging.getLogger(__name__)


class ChatPDFGenerator:
    """
    Generates PDF exports of chat conversations with WWF branding
    """
    
    # WWF Brand Colors
    WWF_ORANGE = HexColor('#FF6200')
    WWF_BLACK = HexColor('#000000')
    USER_COLOR = HexColor('#2C5F2D')  # Forest green for user messages
    ASSISTANT_COLOR = HexColor('#1A1A1A')  # Dark gray for assistant
    
    def __init__(self, output_dir: str = "exports"):
        """
        Initialize PDF generator
        
        Args:
            output_dir: Directory to save PDF files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Create custom styles
        self.styles = getSampleStyleSheet()
        self._create_custom_styles()
        
        logger.info(f"[PDF Generator] Initialized, output dir: {self.output_dir}")
    
    def _create_custom_styles(self):
        """Create custom paragraph styles for chat messages"""
        
        # Title style
        self.styles.add(ParagraphStyle(
            name='ChatTitle',
            parent=self.styles['Title'],
            fontSize=24,
            textColor=self.WWF_ORANGE,
            spaceAfter=12,
            alignment=TA_CENTER
        ))
        
        # Subtitle style
        self.styles.add(ParagraphStyle(
            name='ChatSubtitle',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=self.WWF_BLACK,
            spaceAfter=20,
            alignment=TA_CENTER
        ))
        
        # User message style
        self.styles.add(ParagraphStyle(
            name='UserMessage',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=self.USER_COLOR,
            fontName='Helvetica-Bold',
            spaceAfter=6,
            leftIndent=0
        ))
        
        # Assistant message style
        self.styles.add(ParagraphStyle(
            name='AssistantMessage',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=self.ASSISTANT_COLOR,
            spaceAfter=6,
            leftIndent=20
        ))
        
        # Source citation style
        self.styles.add(ParagraphStyle(
            name='SourceCitation',
            parent=self.styles['Normal'],
            fontSize=9,
            textColor=HexColor('#666666'),
            leftIndent=30,
            spaceAfter=12,
            fontName='Helvetica-Oblique'
        ))
    
    def generate_pdf(
        self,
        session_id: str,
        user_name: str,
        user_location: str,
        messages: List[Dict],
        filename: str = None
    ) -> str:
        """
        Generate PDF from chat session
        
        Args:
            session_id: Chat session ID
            user_name: User's name
            user_location: User's location
            messages: List of message dictionaries with 'role', 'content', 'timestamp', 'sources'
            filename: Custom filename (optional)
        
        Returns:
            Path to generated PDF file
        """
        # Generate filename
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"wwf_chat_{session_id}_{timestamp}.pdf"
        
        output_path = self.output_dir / filename
        
        logger.info(f"[PDF Generator] Generating PDF: {output_path}")
        
        try:
            # Create PDF document
            doc = SimpleDocTemplate(
                str(output_path),
                pagesize=letter,
                topMargin=0.75*inch,
                bottomMargin=0.75*inch,
                leftMargin=0.75*inch,
                rightMargin=0.75*inch
            )
            
            # Build story (content)
            story = []
            
            # Add title
            title = Paragraph(
                "<b>WWF Sustainability Chat</b>",
                self.styles['ChatTitle']
            )
            story.append(title)
            story.append(Spacer(1, 0.1*inch))
            
            # Add session info
            session_info = Paragraph(
                f"User: {user_name} | Location: {user_location}<br/>"
                f"Session ID: {session_id}<br/>"
                f"Date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
                self.styles['ChatSubtitle']
            )
            story.append(session_info)
            story.append(Spacer(1, 0.3*inch))
            
            # Add separator
            story.append(Paragraph("<hr/>", self.styles['Normal']))
            story.append(Spacer(1, 0.2*inch))
            
            # Add messages
            for msg in messages:
                # Parse timestamp
                try:
                    msg_time = datetime.fromisoformat(msg['timestamp'])
                    time_str = msg_time.strftime('%I:%M %p')
                except:
                    time_str = "N/A"
                
                # Escape HTML special characters in content
                content = self._escape_html(msg['content'])
                
                if msg['role'] == 'user':
                    # User message
                    text = f"<b>You ({time_str}):</b><br/>{content}"
                    story.append(Paragraph(text, self.styles['UserMessage']))
                else:
                    # Assistant message
                    text = f"<b>WWF Assistant ({time_str}):</b><br/>{content}"
                    story.append(Paragraph(text, self.styles['AssistantMessage']))
                    
                    # Add sources if available
                    if msg.get('sources') and len(msg['sources']) > 0:
                        sources_text = "<b>Sources:</b><br/>"
                        for idx, source in enumerate(msg['sources'], 1):
                            title = self._escape_html(source.get('title', 'Untitled'))
                            url = source.get('url', '')
                            if url:
                                sources_text += f"{idx}. {title} ({url})<br/>"
                            else:
                                sources_text += f"{idx}. {title}<br/>"
                        
                        story.append(Paragraph(sources_text, self.styles['SourceCitation']))
                
                story.append(Spacer(1, 0.2*inch))
            
            # Add footer
            story.append(Spacer(1, 0.3*inch))
            story.append(Paragraph("<hr/>", self.styles['Normal']))
            footer = Paragraph(
                "<i>Generated by WWF Sustainability Chat Assistant | "
                "This conversation export is for your records.</i>",
                self.styles['ChatSubtitle']
            )
            story.append(footer)
            
            # Build PDF
            doc.build(story)
            
            logger.info(f"[PDF Generator] Successfully generated PDF: {output_path}")
            
            return str(output_path)
        
        except Exception as e:
            logger.error(f"[PDF Generator] Error generating PDF: {e}")
            raise
    
    def _escape_html(self, text: str) -> str:
        """
        Escape HTML special characters for ReportLab
        
        Args:
            text: Text to escape
        
        Returns:
            Escaped text
        """
        replacements = {
            '&': '&amp;',
            '<': '&lt;',
            '>': '&gt;',
            '"': '&quot;',
            "'": '&#39;'
        }
        
        for old, new in replacements.items():
            text = text.replace(old, new)
        
        return text
