# Generated by GitHub Copilot
"""
PDF Export Generator - Creates PDF exports of chat conversations
"""
import re
import os
import logging
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Tuple
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak
from reportlab.lib.enums import TA_LEFT, TA_CENTER

logger = logging.getLogger(__name__)


class ChatPDFGenerator:
    """
    Generates PDF exports of chat conversations with WWF branding
    """
    
    # WWF Brand Colors
    WWF_ORANGE = HexColor('#FF6200')
    WWF_BLACK = HexColor('#000000')
    USER_COLOR = HexColor('#2C5F2D')  # Forest green for user messages
    ASSISTANT_COLOR = HexColor('#1A1A1A')  # Dark gray for assistant
    
    def __init__(self, output_dir: str = "exports"):
        """
        Initialize PDF generator
        
        Args:
            output_dir: Directory to save PDF files
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Create custom styles
        self.styles = getSampleStyleSheet()
        self._create_custom_styles()
        
        logger.info(f"[PDF Generator] Initialized, output dir: {self.output_dir}")
    
    def _create_custom_styles(self):
        """Create custom paragraph styles for chat messages"""
        
        # Title style
        self.styles.add(ParagraphStyle(
            name='ChatTitle',
            parent=self.styles['Title'],
            fontSize=24,
            textColor=self.WWF_ORANGE,
            spaceAfter=12,
            alignment=TA_CENTER
        ))
        
        # Subtitle style
        self.styles.add(ParagraphStyle(
            name='ChatSubtitle',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=self.WWF_BLACK,
            spaceAfter=20,
            alignment=TA_CENTER
        ))
        
        # User message style
        self.styles.add(ParagraphStyle(
            name='UserMessage',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=self.USER_COLOR,
            fontName='Helvetica-Bold',
            spaceAfter=6,
            leftIndent=0
        ))
        
        # Assistant message style
        self.styles.add(ParagraphStyle(
            name='AssistantMessage',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=self.ASSISTANT_COLOR,
            spaceAfter=6,
            leftIndent=20
        ))
        
        # Source citation style
        self.styles.add(ParagraphStyle(
            name='SourceCitation',
            parent=self.styles['Normal'],
            fontSize=9,
            textColor=HexColor('#666666'),
            leftIndent=30,
            spaceAfter=12,
            fontName='Helvetica-Oblique'
        ))

        # Bullet item style
        self.styles.add(ParagraphStyle(
            name='BulletItem',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=self.ASSISTANT_COLOR,
            leftIndent=35,
            firstLineIndent=0,
            spaceAfter=3,
            bulletIndent=20,
        ))

        # Section header style (for ### / ## headings inside responses)
        self.styles.add(ParagraphStyle(
            name='ResponseHeader',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=self.WWF_ORANGE,
            fontName='Helvetica-Bold',
            spaceBefore=8,
            spaceAfter=4,
            leftIndent=20,
        ))
    
    def generate_pdf(
        self,
        session_id: str,
        user_name: str,
        user_location: str,
        messages: List[Dict],
        filename: str = None
    ) -> str:
        """
        Generate PDF from chat session
        
        Args:
            session_id: Chat session ID
            user_name: User's name
            user_location: User's location
            messages: List of message dictionaries with 'role', 'content', 'timestamp', 'sources'
            filename: Custom filename (optional)
        
        Returns:
            Path to generated PDF file
        """
        # Generate filename
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"wwf_chat_{session_id}_{timestamp}.pdf"
        
        output_path = self.output_dir / filename
        
        logger.info(f"[PDF Generator] Generating PDF: {output_path}")
        
        try:
            # Create PDF document
            doc = SimpleDocTemplate(
                str(output_path),
                pagesize=letter,
                topMargin=0.75*inch,
                bottomMargin=0.75*inch,
                leftMargin=0.75*inch,
                rightMargin=0.75*inch
            )
            
            # Build story (content)
            story = []
            
            # Add title
            title = Paragraph(
                "<b>WWF Sustainability Chat</b>",
                self.styles['ChatTitle']
            )
            story.append(title)
            story.append(Spacer(1, 0.1*inch))
            
            # Add session info
            session_info = Paragraph(
                f"User: {user_name} | Location: {user_location}<br/>"
                f"Session ID: {session_id}<br/>"
                f"Date: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
                self.styles['ChatSubtitle']
            )
            story.append(session_info)
            story.append(Spacer(1, 0.3*inch))
            
            # Add separator
            story.append(Paragraph("<hr/>", self.styles['Normal']))
            story.append(Spacer(1, 0.2*inch))
            
            # Add messages
            for msg in messages:
                # Parse timestamp
                try:
                    msg_time = datetime.fromisoformat(msg['timestamp'])
                    time_str = msg_time.strftime('%I:%M %p')
                except Exception:
                    time_str = "N/A"
                
                if msg['role'] == 'user':
                    # User message (single paragraph)
                    text = f"<b>You ({time_str}):</b><br/>{self._escape_xml(msg['content'])}"
                    story.append(Paragraph(text, self.styles['UserMessage']))
                else:
                    # Assistant message — render with markdown formatting
                    header_text = f"<b>WWF Assistant ({time_str}):</b>"
                    story.append(Paragraph(header_text, self.styles['AssistantMessage']))

                    # Convert markdown content into structured paragraphs
                    content_blocks = self._markdown_to_reportlab_blocks(msg['content'])
                    for block_text, block_style in content_blocks:
                        try:
                            story.append(Paragraph(block_text, self.styles[block_style]))
                        except Exception:
                            # Fallback: plain text if XML is malformed
                            story.append(Paragraph(
                                self._escape_xml(block_text),
                                self.styles['AssistantMessage']
                            ))

                    # Add sources if available
                    if msg.get('sources') and len(msg['sources']) > 0:
                        sources_text = "<b>Sources:</b><br/>"
                        for idx, source in enumerate(msg['sources'], 1):
                            title = self._escape_xml(source.get('title', 'Untitled'))
                            url = source.get('url', '')
                            if url:
                                sources_text += f"{idx}. {title} ({url})<br/>"
                            else:
                                sources_text += f"{idx}. {title}<br/>"

                        story.append(Paragraph(sources_text, self.styles['SourceCitation']))
                
                story.append(Spacer(1, 0.2*inch))
            
            # Add footer
            story.append(Spacer(1, 0.3*inch))
            story.append(Paragraph("<hr/>", self.styles['Normal']))
            footer = Paragraph(
                "<i>Generated by WWF Sustainability Chat Assistant | "
                "This conversation export is for your records.</i>",
                self.styles['ChatSubtitle']
            )
            story.append(footer)
            
            # Build PDF
            doc.build(story)
            
            logger.info(f"[PDF Generator] Successfully generated PDF: {output_path}")
            
            return str(output_path)
        
        except Exception as e:
            logger.error(f"[PDF Generator] Error generating PDF: {e}")
            raise
    
    def _escape_xml(self, text: str) -> str:
        """
        Escape characters that are special in ReportLab's XML/HTML parser.
        Only escapes raw text segments, NOT pre-built HTML tags.
        """
        text = text.replace('&', '&amp;')
        text = text.replace('<', '&lt;')
        text = text.replace('>', '&gt;')
        return text

    def _escape_html(self, text: str) -> str:
        """Legacy alias kept for any external callers."""
        return self._escape_xml(text)

    def _convert_inline_markdown(self, text: str) -> str:
        """
        Convert inline markdown markers to ReportLab-compatible XML tags.

        Conversion order:
        1. Escape raw XML chars (&, <, >) so they don't break the parser.
        2. Convert **bold** → <b>bold</b>
        3. Convert *italic* → <i>italic</i>  (avoids bullet-point asterisks)
        """
        text = self._escape_xml(text)
        # Bold: **text** → <b>text</b>
        text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
        # Italic: *text* not followed/preceded by another * → <i>text</i>
        text = re.sub(r'(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)', r'<i>\1</i>', text)
        return text

    def _markdown_to_reportlab_blocks(self, text: str) -> List[Tuple[str, str]]:
        """
        Parse markdown text and return a list of (xml_content, style_name) tuples
        ready for use with ReportLab Paragraph.

        Handles:
        - Headings: ### / ## / # → ResponseHeader style
        - Bullet points: lines starting with *, -, or • → BulletItem style
        - Numbered lists: lines starting with "1. " etc. → BulletItem style
        - Regular paragraphs → AssistantMessage style
        - Double-newline paragraph breaks
        """
        blocks: List[Tuple[str, str]] = []

        # Split into logical blocks by blank lines
        raw_blocks = re.split(r'\n{2,}', text.strip())

        for raw_block in raw_blocks:
            raw_block = raw_block.strip()
            if not raw_block:
                continue

            lines = raw_block.splitlines()

            # Collect lines, classifying each
            para_lines = []  # accumulate normal paragraph lines

            def flush_para() -> None:
                if para_lines:
                    joined = '<br/>'.join(para_lines)
                    blocks.append((joined, 'AssistantMessage'))
                    para_lines.clear()

            for line in lines:
                stripped = line.strip()
                if not stripped:
                    flush_para()
                    continue

                # Headings
                heading_match = re.match(r'^(#{1,3})\s+(.*)', stripped)
                if heading_match:
                    flush_para()
                    heading_text = self._convert_inline_markdown(heading_match.group(2))
                    blocks.append((heading_text, 'ResponseHeader'))
                    continue

                # Bullet points (* item, - item, • item)
                bullet_match = re.match(r'^[*\-•]\s+(.*)', stripped)
                if bullet_match:
                    flush_para()
                    bullet_text = '• ' + self._convert_inline_markdown(bullet_match.group(1))
                    blocks.append((bullet_text, 'BulletItem'))
                    continue

                # Numbered list (1. item, 2. item …)
                numbered_match = re.match(r'^\d+\.\s+(.*)', stripped)
                if numbered_match:
                    flush_para()
                    item_text = self._convert_inline_markdown(numbered_match.group(1))
                    # Prepend the number from the original line
                    number = re.match(r'^(\d+)\.', stripped).group(1)
                    blocks.append((f"{number}. {item_text}", 'BulletItem'))
                    continue

                # Normal line — accumulate into current paragraph
                para_lines.append(self._convert_inline_markdown(stripped))

            flush_para()

        return blocks if blocks else [('', 'AssistantMessage')]
