# Generated by GitHub Copilot
"""
Chatbot Workflow Orchestration - Coordinates all agents
"""
import logging
from pathlib import Path
from typing import Dict, List
from chatbot.models import UserContext, Source
from chatbot.agents.supervisor import SupervisorAgent
from chatbot.agents.rag_agent import RAGAgent
from chatbot.agents.web_search_agent import WebSearchAgent
from chatbot.agents.response_agent import ResponseAgent

logger = logging.getLogger(__name__)


class ChatbotWorkflow:
    """
    Orchestrates the chatbot workflow:
    Query → Supervisor → RAG/Web/Hybrid → Response Generation
    """
    
    def __init__(
        self,
        vector_store_path: str = None,
        collection_name: str = "wwf_knowledge_base"
    ):
        """
        Initialize chatbot workflow with all agents
        
        Args:
            vector_store_path: Path to ChromaDB vector store (defaults to project root/vector_store)
            collection_name: ChromaDB collection name
        """
        logger.info("[Chatbot Workflow] Initializing agents...")
        
        # Calculate absolute path to vector_store if not provided
        if vector_store_path is None:
            # Get path relative to this file: graph.py is in src/chatbot/agents/
            # Go up 3 levels to project root, then into vector_store
            vector_store_path = str(Path(__file__).parent.parent.parent.parent / "vector_store")
        
        logger.info(f"[Chatbot Workflow] Using vector store path: {vector_store_path}")
        
        # Initialize all agents
        self.supervisor = SupervisorAgent()
        self.rag_agent = RAGAgent(
            vector_store_path=vector_store_path,
            collection_name=collection_name
        )
        self.web_search_agent = WebSearchAgent()
        self.response_agent = ResponseAgent()
        
        logger.info("[Chatbot Workflow] All agents initialized successfully")
    
    def process_message(
        self,
        query: str,
        user_context: UserContext,
        language: str = "English"
    ) -> Dict:
        """
        Process user message through the agent workflow
        
        Args:
            query: User's query
            user_context: User information
            language: Response language (English, French, German)
        
        Returns:
            Dictionary with:
                - response: Generated response text
                - sources: List of Source objects
                - agent_used: Which agent(s) were used
                - pdf_requested: Whether PDF export was requested
        """
        logger.info(f"[Workflow] Processing query in {language}: {query[:50]}...")
        
        # Step 1: Route the query
        route = self.supervisor.route_query(query, user_context.location)
        logger.info(f"[Workflow] Supervisor routed to: {route.upper()}")
        
        # Step 2: Check for PDF export request
        if route == 'pdf_export':
            return {
                'response': "I'll prepare a PDF export of our conversation for you.",
                'sources': [],
                'agent_used': 'pdf_export',
                'pdf_requested': True
            }
        
        # Step 3: Gather context based on routing
        rag_context = ""
        web_context = ""
        sources = []
        actual_agent_used = route
        
        if route in ['rag', 'hybrid']:
            logger.info("[Workflow] Calling RAG Agent...")
            rag_context, rag_sources = self.rag_agent.retrieve(
                query=query,
                user_location=user_context.location
            )
            sources.extend(rag_sources)
            logger.info(f"[Workflow] RAG Agent returned {len(rag_sources)} sources")
            
            # Smart fallback: If RAG route but no good results, try web search instead
            if route == 'rag' and len(rag_sources) < 2:
                logger.warning(f"[Workflow] RAG returned insufficient results ({len(rag_sources)} sources). Falling back to web search for better coverage.")
                logger.info("[Workflow] Calling Web Search Agent (fallback)...")
                web_context, web_sources = self.web_search_agent.search(
                    query=query,
                    user_location=user_context.location
                )
                sources.extend(web_sources)
                logger.info(f"[Workflow] Web Search Agent returned {len(web_sources)} sources")
                actual_agent_used = 'web_search'  # Update to reflect actual agent used
        
        if route in ['web_search', 'hybrid']:
            logger.info("[Workflow] Calling Web Search Agent...")
            web_context, web_sources = self.web_search_agent.search(
                query=query,
                user_location=user_context.location
            )
            sources.extend(web_sources)
            logger.info(f"[Workflow] Web Search Agent returned {len(web_sources)} sources")
        
        # Step 4: Generate response
        logger.info(f"[Workflow] Generating response in {language} with Response Agent...")
        response = self.response_agent.generate_response(
            query=query,
            user_context=user_context,
            rag_context=rag_context,
            web_context=web_context,
            language=language
        )
        
        # Step 5: Return result
        result = {
            'response': response,
            'sources': sources,
            'agent_used': actual_agent_used,  # Use actual agent (may differ from route due to fallback)
            'pdf_requested': False
        }
        
        logger.info(f"[Workflow] Completed with {len(sources)} total sources using {actual_agent_used} agent")
        
        return result
    
    def generate_welcome_message(self, user_context: UserContext) -> str:
        """
        Generate welcome message for new session
        
        Args:
            user_context: User information
        
        Returns:
            Welcome message
        """
        return self.response_agent.generate_welcome_message(user_context)
