# Generated by GitHub Copilot
"""
RAG Agent - Retrieves relevant content from ChromaDB vector store
"""
import os
import logging
from pathlib import Path
from typing import List, Dict, Tuple
import chromadb
from chromadb.utils import embedding_functions
from chatbot.models import Source

logger = logging.getLogger(__name__)


class RAGAgent:
    """
    RAG Agent for retrieving relevant content from existing WWF vector store.
    
    Uses ChromaDB with OpenAI embeddings to find relevant chunks from WWF documents.
    """
    
    def __init__(
        self,
        vector_store_path: str = "vector_store",
        collection_name: str = "wwf_knowledge_base",
        embedding_model: str = "text-embedding-3-small",
        top_k: int = 10,
        relevance_threshold: float = 0.7
    ):
        """
        Initialize RAG Agent
        
        Args:
            vector_store_path: Path to ChromaDB persistent storage
            collection_name: ChromaDB collection name
            embedding_model: OpenAI embedding model
            top_k: Number of chunks to retrieve
            relevance_threshold: Minimum relevance score (0-1)
        """
        self.vector_store_path = vector_store_path
        self.collection_name = collection_name
        self.top_k = top_k
        self.relevance_threshold = relevance_threshold
        
        # Get OpenAI API key
        openai_api_key = os.getenv("OPENAI_API_KEY")
        if not openai_api_key:
            raise ValueError("OPENAI_API_KEY not found in environment")
        
        # Initialize OpenAI embedding function
        self.embedding_function = embedding_functions.OpenAIEmbeddingFunction(
            api_key=openai_api_key,
            model_name=embedding_model
        )
        
        # Initialize ChromaDB
        logger.info(f"[RAG Agent] Connecting to ChromaDB at: {vector_store_path}")
        self.chroma_client = chromadb.PersistentClient(path=vector_store_path)
        self.collection = self.chroma_client.get_collection(
            name=collection_name,
            embedding_function=self.embedding_function
        )
        logger.info(f"[RAG Agent] Connected to collection '{collection_name}' with {self.collection.count()} chunks")
    
    def retrieve(self, query: str, user_location: str = "") -> Tuple[str, List[Source]]:
        """
        Retrieve relevant context from vector store
        
        Args:
            query: User's query
            user_location: User's location (for context enhancement)
        
        Returns:
            Tuple of (combined_context_text, list_of_sources)
        """
        # Enhance query with location context if provided
        enhanced_query = query
        if user_location:
            enhanced_query = f"{query} (in context of {user_location})"
        
        logger.info(f"[RAG Agent] Retrieving for query: {enhanced_query}")
        
        try:
            # Query ChromaDB
            results = self.collection.query(
                query_texts=[enhanced_query],
                n_results=self.top_k
            )
            
            if not results['documents'] or not results['documents'][0]:
                logger.warning("[RAG Agent] No results found")
                return "", []
            
            # Extract results
            documents = results['documents'][0]
            metadatas = results['metadatas'][0] if results['metadatas'] else [{}] * len(documents)
            distances = results['distances'][0] if results['distances'] else [0] * len(documents)
            
            # Filter by relevance (lower distance = higher relevance)
            # ChromaDB uses cosine distance: 0 = identical, 2 = opposite
            # Convert to similarity: 1 - (distance / 2)
            filtered_results = []
            sources = []
            max_similarity = 0.0
            
            for doc, metadata, distance in zip(documents, metadatas, distances):
                similarity = 1 - (distance / 2)
                max_similarity = max(max_similarity, similarity)
                
                if similarity >= self.relevance_threshold:
                    filtered_results.append(doc)
                    
                    # Create source citation
                    source = Source(
                        type='rag',
                        title=metadata.get('source', 'WWF Document'),
                        excerpt=doc[:200] + "..." if len(doc) > 200 else doc
                    )
                    sources.append(source)
                    
                    logger.debug(f"[RAG Agent] Added chunk (similarity: {similarity:.2f})")
            
            # Combine all filtered documents
            combined_context = "\n\n---\n\n".join(filtered_results)
            
            if len(filtered_results) == 0:
                logger.warning(f"[RAG Agent] No chunks met relevance threshold {self.relevance_threshold}. Best similarity: {max_similarity:.2f}")
            else:
                logger.info(f"[RAG Agent] Retrieved {len(filtered_results)} relevant chunks (best similarity: {max_similarity:.2f})")
            
            return combined_context, sources
        
        except Exception as e:
            logger.error(f"[RAG Agent] Error during retrieval: {e}")
            return "", []
    
    def is_relevant_query(self, query: str) -> bool:
        """
        Quick check if query is likely relevant to WWF documents
        
        Args:
            query: User's query
        
        Returns:
            True if query seems relevant to WWF knowledge base
        """
        # Keywords that suggest RAG relevance
        rag_keywords = [
            'wwf', 'world wildlife', 'sustainability', 'circular economy',
            'waste', 'climate', 'conservation', 'biodiversity', 'ecosystem',
            'agriculture', 'natural resources', 'environmental', 'strategy',
            'compliance', 'according to', 'document', 'report', 'guideline'
        ]
        
        query_lower = query.lower()
        return any(keyword in query_lower for keyword in rag_keywords)
