# Generated by GitHub Copilot
"""
Response Agent - Generates personalized responses using Groq LLM
"""
import os
import logging
from typing import Dict
from groq import Groq
from chatbot.models import UserContext

logger = logging.getLogger(__name__)


class ResponseAgent:
    """
    Response Agent that generates personalized, region-aware responses using Groq LLM.
    
    Takes context from RAG and/or Web Search agents and synthesizes accurate,
    personalized answers with anti-hallucination safeguards.
    """
    
    SYSTEM_PROMPT = """You are a WWF (World Wildlife Fund) Sustainability Expert Assistant.

Your responsibilities:
1. Provide accurate, helpful information about sustainability, conservation, and WWF initiatives
2. Personalize responses based on the user's location and educational background
3. NEVER hallucinate or make up information
4. Always cite sources when providing information
5. If you don't have verified information, say so clearly
6. Consider regional environmental context when relevant
7. Provide actionable, region-specific advice when possible

Remember:
- If information is from WWF documents, cite "According to WWF documents..." or "Based on WWF knowledge base..."
- If information is from web search, cite the specific source
- If you're not certain, acknowledge uncertainty
- Keep responses clear, concise, and helpful
- Maintain a professional yet friendly tone"""
    
    def __init__(
        self,
        model: str = "llama-3.3-70b-versatile",
        temperature: float = 0.3,
        max_tokens: int = 1500
    ):
        """
        Initialize Response Agent
        
        Args:
            model: Groq model name
            temperature: LLM temperature (lower = more factual)
            max_tokens: Maximum response length
        """
        self.model = model
        self.temperature = temperature
        self.max_tokens = max_tokens
        
        # Get Groq API key
        groq_api_key = os.getenv("GROQ_API_KEY")
        if not groq_api_key:
            raise ValueError("GROQ_API_KEY not found in environment")
        
        # Initialize Groq client
        self.groq_client = Groq(api_key=groq_api_key)
        logger.info(f"[Response Agent] Initialized with model: {model}")
    
    def generate_response(
        self,
        query: str,
        user_context: UserContext,
        rag_context: str = "",
        web_context: str = ""
    ) -> str:
        """
        Generate personalized response using available context
        
        Args:
            query: User's query
            user_context: User information (name, location, education)
            rag_context: Context from RAG agent
            web_context: Context from web search agent
        
        Returns:
            Generated response text
        """
        # Build user-specific prompt
        user_prompt = self._build_prompt(
            query=query,
            user_context=user_context,
            rag_context=rag_context,
            web_context=web_context
        )
        
        logger.info(f"[Response Agent] Generating response for: {query[:50]}...")
        logger.debug(f"[Response Agent] User: {user_context.name} from {user_context.location}")
        
        try:
            # Call Groq LLM
            response = self.groq_client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": self.SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=self.temperature,
                max_tokens=self.max_tokens
            )
            
            generated_text = response.choices[0].message.content
            
            logger.info(f"[Response Agent] Response generated ({len(generated_text)} chars)")
            
            return generated_text
        
        except Exception as e:
            logger.error(f"[Response Agent] Error generating response: {e}")
            return (
                "I apologize, but I encountered an error generating a response. "
                "Please try rephrasing your question or contact support if the issue persists."
            )
    
    def _build_prompt(
        self,
        query: str,
        user_context: UserContext,
        rag_context: str,
        web_context: str
    ) -> str:
        """
        Build personalized prompt with all available context
        
        Args:
            query: User's query
            user_context: User information
            rag_context: RAG-retrieved context
            web_context: Web search context
        
        Returns:
            Complete prompt for LLM
        """
        prompt_parts = []
        
        # User introduction
        prompt_parts.append(f"""USER PROFILE:
- Name: {user_context.name}
- Location: {user_context.location}
- Background: {user_context.education}

Remember to personalize your response based on their location ({user_context.location}) when relevant.""")
        
        # Add RAG context if available
        if rag_context:
            prompt_parts.append(f"""CONTEXT FROM WWF KNOWLEDGE BASE:
{rag_context}

When using this information, cite as "According to WWF documents..." or "Based on WWF knowledge base...".""")
        
        # Add web search context if available
        if web_context:
            prompt_parts.append(f"""CONTEXT FROM WEB SEARCH (Current Information):
{web_context}

When using this information, cite the specific source mentioned.""")
        
        # Add the actual query
        prompt_parts.append(f"""USER QUESTION:
{query}

INSTRUCTIONS:
1. Provide a comprehensive and accurate answer
2. Personalize for {user_context.location} when relevant
3. Cite sources appropriately (WWF documents vs web sources)
4. If information is from their region, highlight that
5. If you don't have verified information, say so
6. Keep the tone professional but friendly
7. Make it actionable when possible

Generate your response:""")
        
        return "\n\n".join(prompt_parts)
    
    def generate_welcome_message(self, user_context: UserContext) -> str:
        """
        Generate personalized welcome message for new session
        
        Args:
            user_context: User information
        
        Returns:
            Welcome message
        """
        return (
            f"Hello {user_context.name}! 👋\n\n"
            f"I'm your WWF Sustainability Assistant. I'm here to help answer questions about "
            f"sustainability, conservation, circular economy, and WWF initiatives, with a focus "
            f"on {user_context.location}.\n\n"
            f"I can:\n"
            f"• Answer questions using WWF's knowledge base\n"
            f"• Search for current information and recent initiatives\n"
            f"• Provide region-specific advice for {user_context.location}\n"
            f"• Export our conversation as a PDF when you need it\n\n"
            f"What would you like to know?"
        )
