# Generated by GitHub Copilot
"""
Response Agent - Generates personalized responses using Groq LLM
"""
import os
import logging
from typing import Dict
from groq import Groq
from chatbot.models import UserContext

logger = logging.getLogger(__name__)


class ResponseAgent:
    """
    Response Agent that generates personalized, region-aware responses using Groq LLM.
    
    Takes context from RAG and/or Web Search agents and synthesizes accurate,
    personalized answers with anti-hallucination safeguards.
    """
    
    SYSTEM_PROMPT = """You are a WWF (World Wildlife Fund) Sustainability Expert Assistant.

Your responsibilities:
1. Provide accurate, helpful information about sustainability, conservation, and WWF initiatives
2. Personalize responses based on the user's location and educational background
3. NEVER hallucinate or make up information
4. Always cite sources when providing information
5. If you don't have verified information, say so clearly
6. Consider regional environmental context when relevant
7. Provide actionable, region-specific advice when possible

Remember:
- If information is from WWF documents, cite "According to WWF documents..." or "Based on WWF knowledge base..."
- If information is from web search, cite the specific source
- If you're not certain, acknowledge uncertainty
- Keep responses clear, concise, and helpful
- Maintain a professional yet friendly tone"""
    
    def __init__(
        self,
        model: str = "meta-llama/llama-4-scout-17b-16e-instruct",
        temperature: float = 0.3,
        max_tokens: int = 1500
    ):
        """
        Initialize Response Agent
        
        Args:
            model: Groq model name (with fallback models)
            temperature: LLM temperature (lower = more factual)
            max_tokens: Maximum response length
        """
        # Model fallback chain (in order of preference)
        self.models = [
            "meta-llama/llama-4-scout-17b-16e-instruct",  # Primary
            "meta-llama/llama-prompt-guard-2-22m",          # Fallback 1
            "llama-3.3-70b-versatile"                        # Fallback 2 (original)
        ]
        self.current_model_index = 0
        self.model = self.models[0]
        self.temperature = temperature
        self.max_tokens = max_tokens
        
        # Get Groq API key
        groq_api_key = os.getenv("GROQ_API_KEY")
        if not groq_api_key:
            raise ValueError("GROQ_API_KEY not found in environment")
        
        # Initialize Groq client
        self.groq_client = Groq(api_key=groq_api_key)
        logger.info(f"[Response Agent] Initialized with model chain: {' -> '.join(self.models)}")
    
    def generate_response(
        self,
        query: str,
        user_context: UserContext,
        rag_context: str = "",
        web_context: str = "",
        language: str = "English"
    ) -> str:
        """
        Generate personalized response using available context
        
        Args:
            query: User's query
            user_context: User information (name, location, education)
            rag_context: Context from RAG agent
            web_context: Context from web search agent
            language: Response language (English, French, German)
        
        Returns:
            Generated response text
        """
        # Build language-aware system prompt
        system_prompt = self._get_system_prompt(language)
        
        # Build user-specific prompt
        user_prompt = self._build_prompt(
            query=query,
            user_context=user_context,
            rag_context=rag_context,
            web_context=web_context
        )
        
        logger.info(f"[Response Agent] Generating response in {language} for: {query[:50]}...")
        logger.debug(f"[Response Agent] User: {user_context.name} from {user_context.location}")
        
        # Try each model in fallback chain
        for attempt, model in enumerate(self.models, 1):
            try:
                logger.info(f"[Response Agent] Attempt {attempt}/{len(self.models)} with model: {model}")
                
                # Call Groq LLM
                response = self.groq_client.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    temperature=self.temperature,
                    max_tokens=self.max_tokens
                )
                
                generated_text = response.choices[0].message.content
                
                logger.info(f"[Response Agent] ✅ Success with {model} ({len(generated_text)} chars)")
                
                # Update current model on success
                self.model = model
                self.current_model_index = attempt - 1
                
                return generated_text
            
            except Exception as e:
                error_msg = str(e)
                logger.warning(f"[Response Agent] ❌ Failed with {model}: {error_msg}")
                
                # If this is the last model, return error message
                if attempt == len(self.models):
                    logger.error(f"[Response Agent] All models failed. Last error: {error_msg}")
                    return (
                        "I apologize, but I encountered an error generating a response. "
                        "Please try again in a moment or contact support if the issue persists."
                    )
                
                # Otherwise, continue to next model
                logger.info(f"[Response Agent] Trying next model in fallback chain...")
                continue
    
    def _get_system_prompt(self, language: str) -> str:
        """
        Get language-aware system prompt
        
        Args:
            language: Target response language
            
        Returns:
            System prompt with language instruction
        """
        language_instruction = ""
        if language == "French":
            language_instruction = "\n\n**CRITICAL: Respond ONLY in French. Use proper French grammar, accents, and terminology.**"
        elif language == "German":
            language_instruction = "\n\n**CRITICAL: Respond ONLY in German. Use proper German grammar, capitalization, and terminology.**"
        elif language == "English":
            language_instruction = ""  # Default, no special instruction
        
        return self.SYSTEM_PROMPT + language_instruction
    
    def _build_prompt(
        self,
        query: str,
        user_context: UserContext,
        rag_context: str,
        web_context: str
    ) -> str:
        """
        Build personalized prompt with all available context
        
        Args:
            query: User's query
            user_context: User information
            rag_context: RAG-retrieved context
            web_context: Web search context
        
        Returns:
            Complete prompt for LLM
        """
        prompt_parts = []
        
        # User introduction
        prompt_parts.append(f"""USER PROFILE:
- Name: {user_context.name}
- Location: {user_context.location}
- Background: {user_context.education}

Remember to personalize your response based on their location ({user_context.location}) when relevant.""")
        
        # Add RAG context if available
        if rag_context:
            prompt_parts.append(f"""CONTEXT FROM WWF KNOWLEDGE BASE:
{rag_context}

When using this information, cite as "According to WWF documents..." or "Based on WWF knowledge base...".""")
        
        # Add web search context if available
        if web_context:
            prompt_parts.append(f"""CONTEXT FROM WEB SEARCH (Current Information):
{web_context}

When using this information, cite the specific source mentioned.""")
        
        # Add the actual query
        prompt_parts.append(f"""USER QUESTION:
{query}

INSTRUCTIONS:
1. Provide a comprehensive and accurate answer
2. Personalize for {user_context.location} when relevant
3. Cite sources appropriately (WWF documents vs web sources)
4. If information is from their region, highlight that
5. If you don't have verified information, say so
6. Keep the tone professional but friendly
7. Make it actionable when possible

Generate your response:""")
        
        return "\n\n".join(prompt_parts)
    
    def generate_welcome_message(self, user_context: UserContext) -> str:
        """
        Generate personalized welcome message for new session
        
        Args:
            user_context: User information
        
        Returns:
            Welcome message
        """
        return (
            f"Hello {user_context.name}! 👋\n\n"
            f"I'm your WWF Sustainability Assistant. I'm here to help answer questions about "
            f"sustainability, conservation, circular economy, and WWF initiatives, with a focus "
            f"on {user_context.location}.\n\n"
            f"I can:\n"
            f"• Answer questions using WWF's knowledge base\n"
            f"• Search for current information and recent initiatives\n"
            f"• Provide region-specific advice for {user_context.location}\n"
            f"• Export our conversation as a PDF when you need it\n\n"
            f"What would you like to know?"
        )
