# Generated by GitHub Copilot
"""
Supervisor Agent - Routes queries to appropriate agents
"""
import logging
from typing import Literal

logger = logging.getLogger(__name__)


class SupervisorAgent:
    """
    Supervisor Agent that analyzes queries and routes to appropriate agents.
    
    Routing decisions:
    - RAG: Document-based WWF knowledge queries
    - Web Search: Current events, location-specific, recent information
    - Hybrid: Requires both document knowledge and current information
    - PDF Export: User requests conversation export
    """
    
    def __init__(self):
        """Initialize Supervisor Agent"""
        logger.info("[Supervisor Agent] Initialized")
    
    def route_query(
        self,
        query: str,
        user_location: str = ""
    ) -> Literal['rag', 'web_search', 'hybrid', 'pdf_export']:
        """
        Analyze query and determine routing
        
        Args:
            query: User's query
            user_location: User's location (helps determine if location-specific)
        
        Returns:
            Agent route: 'rag', 'web_search', 'hybrid', or 'pdf_export'
        """
        query_lower = query.lower()
        
        # 1. Check for PDF export request (highest priority)
        if self._is_pdf_export_request(query_lower):
            logger.info("[Supervisor] Routing to: PDF_EXPORT")
            return 'pdf_export'
        
        # 2. Check for web search indicators
        needs_web = self._needs_web_search(query_lower)
        
        # 3. Check for RAG indicators
        needs_rag = self._needs_rag(query_lower)
        
        # 4. Decide routing
        if needs_web and needs_rag:
            logger.info("[Supervisor] Routing to: HYBRID (both RAG + Web Search)")
            return 'hybrid'
        elif needs_web:
            logger.info("[Supervisor] Routing to: WEB_SEARCH")
            return 'web_search'
        else:
            # Default to RAG for general sustainability questions
            logger.info("[Supervisor] Routing to: RAG")
            return 'rag'
    
    def _is_pdf_export_request(self, query_lower: str) -> bool:
        """
        Detect if user wants to export chat as PDF
        
        Args:
            query_lower: Lowercased query string
        
        Returns:
            True if PDF export requested
        """
        pdf_keywords = [
            'export', 'download', 'save as pdf', 'pdf',
            'get a copy', 'send me', 'email this',
            'save this conversation', 'save chat',
            'download chat', 'export conversation'
        ]
        
        return any(keyword in query_lower for keyword in pdf_keywords)
    
    def _needs_web_search(self, query_lower: str) -> bool:
        """
        Check if query requires real-time web search
        
        Args:
            query_lower: Lowercased query string
        
        Returns:
            True if web search needed
        """
        web_indicators = [
            # Time-sensitive keywords
            'latest', 'current', 'recent', 'news', 'today',
            'this year', 'this month', 'now', 'ongoing',
            'update', 'new', 'happening', '2024', '2025', '2026',
            
            # Location-specific keywords
            'in my area', 'near me', 'local', 'in my city',
            'in my state', 'in my country', 'regional',
            
            # Regulatory/Policy keywords (often time-sensitive)
            'regulation', 'law', 'policy', 'government',
            'legislation', 'compliance', 'requirement',
            
            # Current initiatives/projects
            'initiative', 'program', 'project', 'campaign',
            'wwf project', 'wwf initiative', 'wwf campaign'
        ]
        
        return any(indicator in query_lower for indicator in web_indicators)
    
    def _needs_rag(self, query_lower: str) -> bool:
        """
        Check if query requires RAG from WWF documents
        
        Args:
            query_lower: Lowercased query string
        
        Returns:
            True if RAG needed
        """
        rag_indicators = [
            # Explicit document references
            'according to wwf', 'wwf document', 'wwf report',
            'wwf guideline', 'wwf says', 'in the document',
            
            # Core WWF topics (well documented)
            'circular economy', 'sustainability strategy',
            'waste reduction', 'sustainable agriculture',
            'natural resources', 'biodiversity',
            'ecosystem', 'conservation', 'environmental',
            
            # Framework/Strategy keywords
            'framework', 'strategy', 'approach', 'model',
            'principles', 'guidelines', 'best practices',
            
            # Educational/Conceptual
            'what is', 'explain', 'define', 'how does',
            'why is', 'concept', 'theory', 'understanding'
        ]
        
        return any(indicator in query_lower for indicator in rag_indicators)
    
    def get_routing_explanation(self, route: str) -> str:
        """
        Get human-readable explanation of routing decision
        
        Args:
            route: The route chosen
        
        Returns:
            Explanation string
        """
        explanations = {
            'rag': "I'll search our WWF knowledge base for this information.",
            'web_search': "I'll search the web for current information on this topic.",
            'hybrid': "I'll combine information from our WWF knowledge base and current web sources.",
            'pdf_export': "I'll generate a PDF export of our conversation."
        }
        
        return explanations.get(route, "Processing your request...")
