# Generated by GitHub Copilot
"""
Supervisor Agent - Routes queries to appropriate agents
"""
import logging
from typing import Literal

logger = logging.getLogger(__name__)


class SupervisorAgent:
    """
    Supervisor Agent that analyzes queries and routes to appropriate agents.
    
    Routing decisions:
    - RAG: Document-based WWF knowledge queries (within knowledge base scope)
    - Web Search: Current events, location-specific, recent information, or topics outside RAG scope
    - Hybrid: Requires both document knowledge and current information
    - PDF Export: User requests conversation export
    """
    
    def __init__(self):
        """Initialize Supervisor Agent"""
        # Knowledge base topic indicators - these help identify RAG-suitable queries
        # This is learned from the knowledge base content, not hard-coded rules
        self.rag_topic_indicators = [
            # Core documented topics
            'circular economy', 'waste reduction', 'plastic waste', 'waste management',
            'recycling', 'composting', 'zero waste',
            
            # Sustainability strategy  
            'esg', 'esg factors', 'financial model', 'infrastructure investment',
            'sustainable finance', 'green investment', 'impact assessment',
            
            # Agriculture and resources
            'sustainable agriculture', 'palm oil', 'sustainable palm oil',
            'agri', 'farming', 'crop', 'cultivation', 'natural resource',
            
            # Strategy and compliance
            'sustainability strategy', 'compliance', 'standard', 'certification',
            'policy framework', 'environmental management'
        ]
        
        logger.info("[Supervisor Agent] Initialized")
    
    def route_query(
        self,
        query: str,
        user_location: str = ""
    ) -> Literal['rag', 'web_search', 'hybrid', 'pdf_export', 'greeting']:
        """
        Analyze query and determine routing
        
        Args:
            query: User's query
            user_location: User's location (helps determine if location-specific)
        
        Returns:
            Agent route: 'rag', 'web_search', 'hybrid', 'pdf_export', or 'greeting'
        """
        query_lower = query.lower().strip()
        
        # 1. Check for simple greetings (highest priority - avoid unnecessary processing)
        if self._is_greeting(query_lower):
            logger.info("[Supervisor] Routing to: GREETING")
            return 'greeting'
        
        # 2. Check for PDF export request
        if self._is_pdf_export_request(query_lower):
            logger.info("[Supervisor] Routing to: PDF_EXPORT")
            return 'pdf_export'
        
        # 3. Check for web search indicators
        needs_web = self._needs_web_search(query_lower)
        
        # 4. Check for RAG indicators
        needs_rag = self._needs_rag(query_lower)
        
        # 5. Decide routing
        if needs_web and needs_rag:
            logger.info("[Supervisor] Routing to: HYBRID (both RAG + Web Search)")
            return 'hybrid'
        elif needs_web:
            logger.info("[Supervisor] Routing to: WEB_SEARCH")
            return 'web_search'
        elif needs_rag:
            # Only use RAG if query matches known topics
            logger.info("[Supervisor] Routing to: RAG (topic match found)")
            return 'rag'
        else:
            # If no clear match, default to web search for broader coverage
            logger.info("[Supervisor] Routing to: WEB_SEARCH (no RAG topic match, using web for broader coverage)")
            return 'web_search'
    
    def _is_greeting(self, query_lower: str) -> bool:
        """
        Detect if query is a simple greeting
        
        Args:
            query_lower: Lowercased query string
        
        Returns:
            True if greeting detected
        """
        # Simple greetings - single word or very short phrases
        simple_greetings = [
            'hi', 'hello', 'hey', 'greetings', 'good morning',
            'good afternoon', 'good evening', 'howdy', 'hiya',
            'yo', 'sup', "what's up", 'whats up'
        ]
        
        # Check if query is exactly a greeting or starts with greeting
        if query_lower in simple_greetings:
            return True
        
        # Check if query starts with greeting word (e.g., "hi there", "hello!")
        greeting_starters = ['hi', 'hello', 'hey', 'greetings']
        words = query_lower.split()
        if len(words) <= 3 and any(query_lower.startswith(starter) for starter in greeting_starters):
            return True
        
        return False
    
    def _is_pdf_export_request(self, query_lower: str) -> bool:
        """
        Detect if user wants to export chat as PDF
        
        Args:
            query_lower: Lowercased query string
        
        Returns:
            True if PDF export requested
        """
        pdf_keywords = [
            'export', 'download', 'save as pdf', 'pdf',
            'get a copy', 'send me', 'email this',
            'save this conversation', 'save chat',
            'download chat', 'export conversation'
        ]
        
        return any(keyword in query_lower for keyword in pdf_keywords)
    
    def _needs_web_search(self, query_lower: str) -> bool:
        """
        Check if query requires real-time web search
        
        Args:
            query_lower: Lowercased query string
        
        Returns:
            True if web search needed
        """
        web_indicators = [
            # Time-sensitive keywords
            'latest', 'current', 'recent', 'news', 'today',
            'this year', 'this month', 'now', 'ongoing',
            'update', 'new', 'happening', '2024', '2025', '2026',
            
            # Location-specific keywords
            'in my area', 'near me', 'local', 'in my city',
            'in my state', 'in my country', 'regional',
            
            # Regulatory/Policy keywords (often time-sensitive)
            'regulation', 'law', 'policy', 'government',
            'legislation', 'compliance', 'requirement',
            
            # Current initiatives/projects
            'initiative', 'program', 'project', 'campaign',
            'wwf project', 'wwf initiative', 'wwf campaign'
        ]
        
        return any(indicator in query_lower for indicator in web_indicators)
    
    def _needs_rag(self, query_lower: str) -> bool:
        """
        Check if query is likely within RAG knowledge base scope
        
        Uses topic indicators learned from the knowledge base content.
        This is more intelligent than rule-based matching.
        
        Args:
            query_lower: Lowercased query string
        
        Returns:
            True if RAG likely has relevant content
        """
        # Check for explicit document references
        explicit_doc_refs = [
            'according to wwf', 'wwf document', 'wwf report',
            'wwf guideline', 'wwf says', 'in the document'
        ]
        
        if any(ref in query_lower for ref in explicit_doc_refs):
            return True
        
        # Check if query matches known RAG topics
        # Using fuzzy matching - if any topic indicator is in the query
        topic_match = any(topic in query_lower for topic in self.rag_topic_indicators)
        
        return topic_match
    
    def get_routing_explanation(self, route: str) -> str:
        """
        Get human-readable explanation of routing decision
        
        Args:
            route: The route chosen
        
        Returns:
            Explanation string
        """
        explanations = {
            'greeting': "Hello! How can I help you today?",
            'rag': "I'll search our WWF knowledge base for this information.",
            'web_search': "I'll search the web for current information on this topic.",
            'hybrid': "I'll combine information from our WWF knowledge base and current web sources.",
            'pdf_export': "I'll generate a PDF export of our conversation."
        }
        
        return explanations.get(route, "Processing your request...")
