# Generated by GitHub Copilot
"""
Web Search Agent - Performs real-time web searches using TavilyAI
"""
import os
import logging
from typing import List, Tuple
from tavily import TavilyClient
from chatbot.models import Source

logger = logging.getLogger(__name__)


class WebSearchAgent:
    """
    Web Search Agent using TavilyAI for real-time information retrieval.
    
    Focuses searches on WWF domains and sustainability topics with location awareness.
    """
    
    def __init__(
        self,
        max_results: int = 5,
        search_depth: str = "advanced"
    ):
        """
        Initialize Web Search Agent
        
        Args:
            max_results: Maximum number of search results
            search_depth: "basic" or "advanced" search
        """
        self.max_results = max_results
        self.search_depth = search_depth
        
        # Get Tavily API key
        tavily_api_key = os.getenv("TAVILY_API_KEY")
        if not tavily_api_key:
            raise ValueError("TAVILY_API_KEY not found in environment")
        
        # Initialize Tavily client
        self.tavily_client = TavilyClient(api_key=tavily_api_key)
        logger.info("[Web Search Agent] Initialized with TavilyAI")
    
    def search(self, query: str, user_location: str = "") -> Tuple[str, List[Source]]:
        """
        Perform web search with location-aware query enhancement
        
        Args:
            query: User's query
            user_location: User's location for regional results
        
        Returns:
            Tuple of (search_results_text, list_of_sources)
        """
        # Enhance query with location if provided
        enhanced_query = query
        if user_location:
            enhanced_query = f"{query} {user_location}"
        
        logger.info(f"[Web Search Agent] Searching for: {enhanced_query}")
        
        try:
            # Perform search with WWF domain focus
            response = self.tavily_client.search(
                query=enhanced_query,
                max_results=self.max_results,
                search_depth=self.search_depth,
                include_domains=[
                    "wwf.org",
                    "worldwildlife.org",
                    "panda.org",
                    "wwf.org.uk",
                    "wwf.de",
                    "wwf.ca",
                    "wwf.org.au",
                    "wwfblr.org",  # WWF India
                    "wwf.org.za",  # WWF South Africa
                    # Add more regional WWF domains as needed
                ],
                include_answer=True  # Get AI-generated summary
            )
            
            # Extract results
            results_text = []
            sources = []
            
            # Add AI-generated answer if available
            if response.get('answer'):
                results_text.append(f"Summary: {response['answer']}")
            
            # Process search results
            for result in response.get('results', []):
                # Add to text context
                title = result.get('title', 'Untitled')
                content = result.get('content', '')
                url = result.get('url', '')
                
                results_text.append(f"**{title}**\n{content}\nSource: {url}")
                
                # Create source citation
                source = Source(
                    type='web_search',
                    title=title,
                    url=url,
                    excerpt=content[:200] + "..." if len(content) > 200 else content
                )
                sources.append(source)
                
                logger.debug(f"[Web Search Agent] Added result: {title}")
            
            # Combine all results
            combined_context = "\n\n---\n\n".join(results_text)
            
            logger.info(f"[Web Search Agent] Found {len(sources)} results")
            
            return combined_context, sources
        
        except Exception as e:
            logger.error(f"[Web Search Agent] Search error: {e}")
            return "", []
    
    def is_relevant_query(self, query: str) -> bool:
        """
        Check if query requires real-time web search
        
        Args:
            query: User's query
        
        Returns:
            True if query needs current/location-specific information
        """
        # Keywords suggesting need for web search
        web_keywords = [
            'latest', 'current', 'recent', 'news', 'today', 'this year',
            'now', 'update', 'new', 'happening', 'regulation', 'law',
            'government', 'policy', 'initiative', 'program', 'project',
            'in my area', 'near me', 'local'
        ]
        
        query_lower = query.lower()
        return any(keyword in query_lower for keyword in web_keywords)
