# Generated by GitHub Copilot
"""
Web Search Agent - Performs real-time web searches using TavilyAI with DuckDuckGo fallback
"""
import os
import logging
from typing import List, Tuple
from tavily import TavilyClient
from duckduckgo_search import DDGS
from chatbot.models import Source

logger = logging.getLogger(__name__)


class WebSearchAgent:
    """
    Web Search Agent using TavilyAI for real-time information retrieval.
    Falls back to DuckDuckGo if Tavily fails (rate limits, errors, etc.)
    
    Focuses searches on WWF domains and sustainability topics with location awareness.
    """
    
    def __init__(
        self,
        max_results: int = 5,
        search_depth: str = "advanced"
    ):
        """
        Initialize Web Search Agent
        
        Args:
            max_results: Maximum number of search results
            search_depth: "basic" or "advanced" search (for Tavily)
        """
        self.max_results = max_results
        self.search_depth = search_depth
        
        # Get Tavily API key (optional - will use DuckDuckGo if not available)
        tavily_api_key = os.getenv("TAVILY_API_KEY")
        if tavily_api_key:
            try:
                self.tavily_client = TavilyClient(api_key=tavily_api_key)
                logger.info("[Web Search Agent] Initialized with TavilyAI (primary)")
            except Exception as e:
                logger.warning(f"[Web Search Agent] Failed to initialize Tavily: {e}")
                self.tavily_client = None
        else:
            logger.info("[Web Search Agent] No Tavily API key - using DuckDuckGo only")
            self.tavily_client = None
        
        # DuckDuckGo is always available as fallback (no API key needed)
        logger.info("[Web Search Agent] DuckDuckGo fallback available")
    
    def search(self, query: str, user_location: str = "") -> Tuple[str, List[Source]]:
        """
        Perform web search with location-aware query enhancement.
        Tries Tavily first, falls back to DuckDuckGo if Tavily fails.
        
        Args:
            query: User's query
            user_location: User's location for regional results
        
        Returns:
            Tuple of (search_results_text, list_of_sources)
        """
        # Enhance query with location if provided
        enhanced_query = query
        if user_location:
            enhanced_query = f"{query} in {user_location}"
        
        logger.info(f"[Web Search Agent] Searching for: {enhanced_query}")
        
        # Try Tavily first if available
        if self.tavily_client:
            try:
                return self._search_tavily(enhanced_query)
            except Exception as e:
                logger.warning(f"[Web Search Agent] Tavily search failed: {e}. Falling back to DuckDuckGo...")
        
        # Fallback to DuckDuckGo
        return self._search_duckduckgo(enhanced_query)
    
    def _search_tavily(self, query: str) -> Tuple[str, List[Source]]:
        """
        Perform search using TavilyAI
        
        Args:
            query: Enhanced query string
        
        Returns:
            Tuple of (search_results_text, list_of_sources)
        """
        # Perform search with WWF domain focus
        response = self.tavily_client.search(
            query=query,
            max_results=self.max_results,
            search_depth=self.search_depth,
            include_domains=[
                "wwf.org",
                "worldwildlife.org",
                "panda.org",
                "wwf.org.uk",
                "wwf.de",
                "wwf.ca",
                "wwf.org.au",
                "wwfblr.org",  # WWF India
                "wwf.org.za",  # WWF South Africa
            ],
            include_answer=True  # Get AI-generated summary
        )
        
        # Extract results
        results_text = []
        sources = []
        
        # Add AI-generated answer if available
        if response.get('answer'):
            results_text.append(f"Summary: {response['answer']}")
        
        # Process search results
        for result in response.get('results', []):
            # Add to text context
            title = result.get('title', 'Untitled')
            content = result.get('content', '')
            url = result.get('url', '')
            
            results_text.append(f"**{title}**\n{content}\nSource: {url}")
            
            # Create source citation
            source = Source(
                type='web_search',
                title=title,
                url=url,
                excerpt=content[:200] + "..." if len(content) > 200 else content
            )
            sources.append(source)
            
            logger.debug(f"[Web Search Agent] Tavily result: {title}")
        
        # Combine all results
        combined_context = "\n\n---\n\n".join(results_text)
        
        logger.info(f"[Web Search Agent] Tavily found {len(sources)} results")
        
        return combined_context, sources
    
    def _search_duckduckgo(self, query: str) -> Tuple[str, List[Source]]:
        """
        Perform search using DuckDuckGo (fallback method)
        
        Args:
            query: Enhanced query string
        
        Returns:
            Tuple of (search_results_text, list_of_sources)
        """
        try:
            # Add WWF focus to query
            wwf_query = f"{query} site:wwf.org OR site:worldwildlife.org"
            
            logger.info(f"[Web Search Agent] Using DuckDuckGo for: {wwf_query}")
            
            # Perform search
            with DDGS() as ddgs:
                results = list(ddgs.text(wwf_query, max_results=self.max_results))
            
            # Extract results
            results_text = []
            sources = []
            
            for result in results:
                title = result.get('title', 'Untitled')
                body = result.get('body', '')
                url = result.get('href', '')
                
                results_text.append(f"**{title}**\n{body}\nSource: {url}")
                
                # Create source citation
                source = Source(
                    type='web_search',
                    title=title,
                    url=url,
                    excerpt=body[:200] + "..." if len(body) > 200 else body
                )
                sources.append(source)
                
                logger.debug(f"[Web Search Agent] DuckDuckGo result: {title}")
            
            # Combine all results
            combined_context = "\n\n---\n\n".join(results_text) if results_text else "No results found"
            
            logger.info(f"[Web Search Agent] DuckDuckGo found {len(sources)} results")
            
            return combined_context, sources
            
        except Exception as e:
            logger.error(f"[Web Search Agent] DuckDuckGo search error: {e}")
            return "", []
    
    def is_relevant_query(self, query: str) -> bool:
        """
        Check if query requires real-time web search
        
        Args:
            query: User's query
        
        Returns:
            True if query needs current/location-specific information
        """
        # Keywords suggesting need for web search
        web_keywords = [
            'latest', 'current', 'recent', 'news', 'today', 'this year',
            'now', 'update', 'new', 'happening', 'regulation', 'law',
            'government', 'policy', 'initiative', 'program', 'project',
            'in my area', 'near me', 'local'
        ]
        
        query_lower = query.lower()
        return any(keyword in query_lower for keyword in web_keywords)
