# Generated by GitHub Copilot
"""
Chatbot API Router - FastAPI endpoints for agentic RAG chatbot
"""
import os
import logging
import uuid
from pathlib import Path
from datetime import datetime
from typing import List
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session

from chatbot.models import (
    InitSessionRequest, InitSessionResponse,
    SendMessageRequest, SendMessageResponse,
    ChatHistoryResponse, ChatMessageDTO,
    UserSessionsResponse, ChatSessionSummary,
    UserContext, Source
)
from chatbot.database import get_db, User, ChatSession, ChatMessage
from chatbot.agents.graph import ChatbotWorkflow
from chatbot.pdf_generator import ChatPDFGenerator

logger = logging.getLogger(__name__)

# Create router
router = APIRouter(prefix="/chatbot", tags=["Chatbot"])

# Initialize workflow (singleton)
workflow = None
pdf_generator = None

def get_workflow() -> ChatbotWorkflow:
    """Get or create chatbot workflow instance"""
    global workflow
    if workflow is None:
        # Let graph.py calculate the absolute path to vector_store
        workflow = ChatbotWorkflow(
            collection_name=os.getenv("COLLECTION_NAME", "wwf_knowledge_base")
        )
    return workflow

def get_pdf_generator() -> ChatPDFGenerator:
    """Get or create PDF generator instance"""
    global pdf_generator
    if pdf_generator is None:
        pdf_generator = ChatPDFGenerator(output_dir="exports")
    return pdf_generator


@router.post("/session/init", response_model=InitSessionResponse)
async def initialize_session(
    request: InitSessionRequest,
    db: Session = Depends(get_db)
):
    """
    Initialize a new chat session for a user
    
    Creates or updates user record and starts a new chat session.
    Returns session ID and welcome message.
    
    **Request Body:**
    ```json
    {
        "user_id": "user_12345",
        "name": "John Doe",
        "education": "Environmental Science",
        "location": "California, USA"
    }
    ```
    
    **Response:**
    ```json
    {
        "session_id": "session_abc123",
        "user_id": "user_12345",
        "message": "Chat session initialized",
        "welcome_message": "Hello John! I'm here to help..."
    }
    ```
    """
    try:
        logger.info(f"Initializing session for user: {request.user_id}")
        
        # Check if user exists, create or update
        user = db.query(User).filter(User.user_id == request.user_id).first()
        
        if user:
            # Update existing user
            user.name = request.name
            user.education = request.education
            user.location = request.location
        else:
            # Create new user
            user = User(
                user_id=request.user_id,
                name=request.name,
                education=request.education,
                location=request.location
            )
            db.add(user)
        
        # Create new session
        session_id = str(uuid.uuid4())
        session = ChatSession(
            session_id=session_id,
            user_id=request.user_id
        )
        db.add(session)
        db.commit()
        
        # Generate welcome message
        user_context = UserContext(
            user_id=request.user_id,
            name=request.name,
            education=request.education,
            location=request.location
        )
        
        workflow_instance = get_workflow()
        welcome_message = workflow_instance.generate_welcome_message(user_context)
        
        logger.info(f"Session initialized: {session_id}")
        
        return InitSessionResponse(
            session_id=session_id,
            user_id=request.user_id,
            message="Chat session initialized successfully",
            welcome_message=welcome_message
        )
    
    except Exception as e:
        logger.error(f"Error initializing session: {e}")
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to initialize session: {str(e)}")


@router.post("/message", response_model=SendMessageResponse)
async def send_message(
    request: SendMessageRequest,
    db: Session = Depends(get_db)
):
    """
    Send a message and get AI response
    
    Processes user message through the agentic workflow:
    1. Routes query (RAG, Web Search, Hybrid, or PDF Export)
    2. Retrieves relevant context
    3. Generates personalized response
    4. Saves to chat history
    
    **Request Body:**
    ```json
    {
        "session_id": "session_abc123",
        "user_id": "user_12345",
        "message": "What are circular economy principles?"
    }
    ```
    
    **Response:**
    ```json
    {
        "message_id": "msg_789",
        "response": "According to WWF documents...",
        "sources": [{"type": "rag", "title": "...", "excerpt": "..."}],
        "agent_used": "rag",
        "timestamp": "2026-04-07T20:30:00Z",
        "pdf_url": null
    }
    ```
    """
    try:
        logger.info(f"Processing message for session: {request.session_id}")
        
        # Validate session exists
        session = db.query(ChatSession).filter(
            ChatSession.session_id == request.session_id
        ).first()
        
        if not session:
            raise HTTPException(status_code=404, detail="Session not found")
        
        # Get user context
        user = db.query(User).filter(User.user_id == request.user_id).first()
        if not user:
            raise HTTPException(status_code=404, detail="User not found")
        
        user_context = UserContext(
            user_id=user.user_id,
            name=user.name,
            education=user.education,
            location=user.location
        )
        
        # Save user message to database
        user_message = ChatMessage(
            session_id=request.session_id,
            user_id=request.user_id,
            role="user",
            content=request.message,
            message_metadata={}
        )
        db.add(user_message)
        db.commit()
        
        # Process through workflow
        workflow_instance = get_workflow()
        result = workflow_instance.process_message(
            query=request.message,
            user_context=user_context
        )
        
        # Handle PDF export request
        pdf_url = None
        if result['pdf_requested']:
            # Generate PDF
            pdf_gen = get_pdf_generator()
            messages = _get_session_messages(db, request.session_id)
            
            pdf_path = pdf_gen.generate_pdf(
                session_id=request.session_id,
                user_name=user.name,
                user_location=user.location,
                messages=messages
            )
            
            # Create download URL
            pdf_filename = Path(pdf_path).name
            pdf_url = f"/chatbot/download/{pdf_filename}"
            
            # Add PDF URL to response
            result['response'] += f"\n\n📥 [Download PDF]({pdf_url})"
        
        # Save assistant message to database
        assistant_message = ChatMessage(
            session_id=request.session_id,
            user_id=request.user_id,
            role="assistant",
            content=result['response'],
            message_metadata={
                'agent_used': result['agent_used'],
                'sources': [s.dict() for s in result['sources']],
                'pdf_url': pdf_url
            }
        )
        db.add(assistant_message)
        
        # Update session last activity
        session.last_activity = datetime.utcnow()
        db.commit()
        
        logger.info(f"Message processed successfully (agent: {result['agent_used']})")
        
        return SendMessageResponse(
            message_id=str(assistant_message.message_id),
            response=result['response'],
            sources=result['sources'],
            agent_used=result['agent_used'],
            timestamp=assistant_message.timestamp.isoformat(),
            pdf_url=pdf_url
        )
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error processing message: {e}")
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to process message: {str(e)}")


@router.get("/session/{session_id}/history", response_model=ChatHistoryResponse)
async def get_chat_history(
    session_id: str,
    db: Session = Depends(get_db)
):
    """
    Retrieve chat history for a session
    
    Returns all messages in chronological order.
    
    **Response:**
    ```json
    {
        "session_id": "session_abc123",
        "messages": [
            {
                "role": "user",
                "content": "What are circular economy principles?",
                "sources": null,
                "timestamp": "2026-04-07T20:15:00Z"
            },
            {
                "role": "assistant",
                "content": "According to WWF documents...",
                "sources": [...],
                "timestamp": "2026-04-07T20:15:05Z"
            }
        ]
    }
    ```
    """
    try:
        # Validate session exists
        session = db.query(ChatSession).filter(
            ChatSession.session_id == session_id
        ).first()
        
        if not session:
            raise HTTPException(status_code=404, detail="Session not found")
        
        # Get messages
        messages = db.query(ChatMessage).filter(
            ChatMessage.session_id == session_id
        ).order_by(ChatMessage.timestamp).all()
        
        # Convert to DTOs
        message_dtos = []
        for msg in messages:
            sources = None
            if msg.message_metadata and 'sources' in msg.message_metadata:
                sources = [Source(**s) for s in msg.message_metadata['sources']]
            
            message_dtos.append(ChatMessageDTO(
                role=msg.role,
                content=msg.content,
                sources=sources,
                timestamp=msg.timestamp.isoformat()
            ))
        
        return ChatHistoryResponse(
            session_id=session_id,
            messages=message_dtos
        )
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error retrieving chat history: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to retrieve chat history: {str(e)}")


@router.get("/user/{user_id}/sessions", response_model=UserSessionsResponse)
async def get_user_sessions(
    user_id: str,
    db: Session = Depends(get_db)
):
    """
    Get all chat sessions for a user
    
    Returns summary of each session with message count and preview.
    
    **Response:**
    ```json
    {
        "user_id": "user_12345",
        "sessions": [
            {
                "session_id": "session_abc123",
                "started_at": "2026-04-07T20:00:00Z",
                "last_activity": "2026-04-07T20:30:00Z",
                "message_count": 12,
                "preview": "Latest message preview..."
            }
        ]
    }
    ```
    """
    try:
        # Get all sessions for user
        sessions = db.query(ChatSession).filter(
            ChatSession.user_id == user_id
        ).order_by(ChatSession.last_activity.desc()).all()
        
        # Build summaries
        session_summaries = []
        for session in sessions:
            # Count messages
            message_count = db.query(ChatMessage).filter(
                ChatMessage.session_id == session.session_id
            ).count()
            
            # Get last message preview
            last_message = db.query(ChatMessage).filter(
                ChatMessage.session_id == session.session_id
            ).order_by(ChatMessage.timestamp.desc()).first()
            
            preview = None
            if last_message:
                preview = last_message.content[:100] + "..." if len(last_message.content) > 100 else last_message.content
            
            session_summaries.append(ChatSessionSummary(
                session_id=session.session_id,
                started_at=session.started_at.isoformat(),
                last_activity=session.last_activity.isoformat(),
                message_count=message_count,
                preview=preview
            ))
        
        return UserSessionsResponse(
            user_id=user_id,
            sessions=session_summaries
        )
    
    except Exception as e:
        logger.error(f"Error retrieving user sessions: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to retrieve user sessions: {str(e)}")


@router.get("/download/{filename}")
async def download_pdf(filename: str):
    """
    Download exported PDF file
    
    Serves the generated PDF file for download.
    """
    try:
        file_path = Path("exports") / filename
        
        if not file_path.exists():
            raise HTTPException(status_code=404, detail="PDF file not found")
        
        return FileResponse(
            path=file_path,
            media_type="application/pdf",
            filename=filename
        )
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error downloading PDF: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to download PDF: {str(e)}")


def _get_session_messages(db: Session, session_id: str) -> List[dict]:
    """
    Helper function to get all messages for PDF export
    
    Args:
        db: Database session
        session_id: Chat session ID
    
    Returns:
        List of message dictionaries
    """
    messages = db.query(ChatMessage).filter(
        ChatMessage.session_id == session_id
    ).order_by(ChatMessage.timestamp).all()
    
    result = []
    for msg in messages:
        sources = []
        if msg.message_metadata and 'sources' in msg.message_metadata:
            sources = msg.message_metadata['sources']
        
        result.append({
            'role': msg.role,
            'content': msg.content,
            'timestamp': msg.timestamp.isoformat(),
            'sources': sources
        })
    
    return result
