"""
Utility Functions

This module contains ONLY utility/helper functions for:
- PDF text extraction
- Data transformation and formatting
- File operations

Business logic (MCQ generation, rate limiting, orchestration) is in services/.

Security: Implements file validation and path sanitization.
Resource Efficiency: PDF caching and intelligent content truncation.
"""

import os
import logging
from pathlib import Path
from typing import List, Dict, Any
import pypdf

from dependencies import (
    DATA_BASE_PATH,
    ALLOWED_CATEGORIES,
    pdf_content_cache
)

logger = logging.getLogger(__name__)


def extract_text_from_pdf(category_path: Path) -> str:
    """
    Extract combined text content from all PDF files in a category directory.
    
    Utility function for PDF text extraction with caching.
    
    Args:
        category_path: Path to category directory containing PDF files
    
    Returns:
        Combined text content from all PDFs
    
    Security: Validates file paths and types to prevent unauthorized access.
    Resource Efficiency: Caches PDF content to avoid re-reading.
    """
    # Generated by GitHub Copilot
    try:
        if not category_path.exists():
            logger.error(f"Category path not found: {category_path}")
            raise FileNotFoundError(f"Category path not found: {category_path}")
        
        pdf_files = list(category_path.glob("*.pdf"))
        
        if not pdf_files:
            logger.warning(f"No PDF files found in {category_path}")
            return ""
        
        logger.info(f"Found {len(pdf_files)} PDF files in {category_path.name}")
        
        combined_content = ""
        for pdf_file in pdf_files:
            # Check cache first
            cache_key = str(pdf_file)
            if cache_key in pdf_content_cache:
                logger.info(f"Using cached content for {pdf_file.name}")
                combined_content += pdf_content_cache[cache_key] + "\n\n"
                continue
            
            # Extract text from PDF
            text_content = ""
            with open(pdf_file, 'rb') as file:
                pdf_reader = pypdf.PdfReader(file)
                num_pages = len(pdf_reader.pages)
                logger.info(f"Processing {pdf_file.name} - {num_pages} pages")
                
                for page_num in range(num_pages):
                    page = pdf_reader.pages[page_num]
                    text_content += page.extract_text() + "\n"
            
            text_content = text_content.strip()
            pdf_content_cache[cache_key] = text_content
            combined_content += text_content + "\n\n"
            logger.info(f"Successfully extracted text from {pdf_file.name}")
        
        return combined_content.strip()
        
    except Exception as e:
        logger.error(f"Error extracting text from PDFs: {str(e)}")
        raise


def get_category_pdfs(category: str) -> List[Path]:
    """
    Get all PDF files for a given category.
    
    Utility function for retrieving PDF file list.
    
    Args:
        category: Category name
    
    Returns:
        List of Path objects for PDF files
    
    Security: Validates category and ensures paths stay within allowed directory.
    """
    # Generated by GitHub Copilot
    if category not in ALLOWED_CATEGORIES:
        raise ValueError(f"Invalid category. Must be one of: {ALLOWED_CATEGORIES}")
    
    category_path = DATA_BASE_PATH / category
    
    try:
        category_path = category_path.resolve()
        DATA_BASE_PATH.resolve()
        if not str(category_path).startswith(str(DATA_BASE_PATH.resolve())):
            raise ValueError("Invalid category path")
    except Exception as e:
        logger.error(f"Path validation failed: {e}")
        raise ValueError("Invalid category path")
    
    if not category_path.exists():
        logger.warning(f"Category path not found: {category_path}")
        return []
    
    pdf_files = list(category_path.glob("*.pdf"))
    logger.info(f"Found {len(pdf_files)} PDF files in {category}")
    
    return pdf_files


def transform_to_quickbase_format(standard_response: Dict[str, Any], course_id: str) -> Dict[str, Any]:
    """
    Transform standard MCQ response to Quickbase field ID format.
    
    Field Mappings:
        - 19: course_id
        - 8: set_number
        - 10: question_no
        - 18: question text
        - 11-14: options A-D
        - 15: correct_answer
        - 16: explanation
    """
    mcq_sets = standard_response.get("mcq_sets", [])
    quickbase_records = []
    
    for mcq_set in mcq_sets:
        set_number = mcq_set.get("set_number", 1)
        questions = mcq_set.get("questions", [])
        
        for idx, question in enumerate(questions, start=1):
            correct_answer_letter = question.get("correct_answer", "A")
            
            record = {
                "19": {"value": course_id},
                "8": {"value": set_number},
                "10": {"value": str(idx)},
                "18": {"value": question.get("question", "")},
                "11": {"value": question.get("options", {}).get("A", "")},
                "12": {"value": question.get("options", {}).get("B", "")},
                "13": {"value": question.get("options", {}).get("C", "")},
                "14": {"value": question.get("options", {}).get("D", "")},
                "15": {"value": correct_answer_letter},
                "16": {"value": question.get("explanation", "")}
            }
            quickbase_records.append(record)
    
    return {
        "to": "bvxbt7fyw",
        "data": quickbase_records,
        "fieldsToReturn": [6, 19, 8, 10, 18, 11, 12, 13, 14, 15, 16]
    }
